// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZWALV6oG_bL602uBX0tNg75NwXCA-tWs',
    appId: '1:558902177909:android:cf831536452d83b485883c',
    messagingSenderId: '558902177909',
    projectId: 'projectfirebase-ddb0c',
    storageBucket: 'projectfirebase-ddb0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdX4a2uwhNGvhwMVKig6x9fYjL6Hr3Hbw',
    appId: '1:558902177909:ios:29e0c466ffcc167f85883c',
    messagingSenderId: '558902177909',
    projectId: 'projectfirebase-ddb0c',
    storageBucket: 'projectfirebase-ddb0c.appspot.com',
    androidClientId: '558902177909-32ojguool8prs00cnsbdhotutlpgf7aj.apps.googleusercontent.com',
    iosClientId: '558902177909-i6dl2m2l829ge4dg1fp885cgjk7m9f8f.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectFirebase',
  );
}
